# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/stack-main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 781)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.mainStack = QtWidgets.QStackedWidget(self.centralwidget)
        self.mainStack.setMinimumSize(QtCore.QSize(950, 700))
        self.mainStack.setObjectName("mainStack")
        self.mainPage = QtWidgets.QWidget()
        self.mainPage.setMinimumSize(QtCore.QSize(800, 500))
        self.mainPage.setObjectName("mainPage")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.mainPage)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_left = QtWidgets.QWidget(self.mainPage)
        self.main_left.setMinimumSize(QtCore.QSize(300, 500))
        self.main_left.setObjectName("main_left")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_left)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main_nameWidget = QtWidgets.QWidget(self.main_left)
        font = QtGui.QFont()
        font.setBold(True)
        self.main_nameWidget.setFont(font)
        self.main_nameWidget.setObjectName("main_nameWidget")
        self.formLayout = QtWidgets.QFormLayout(self.main_nameWidget)
        self.formLayout.setObjectName("formLayout")
        self.main_label1 = QtWidgets.QLabel(self.main_nameWidget)
        self.main_label1.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(52)
        font.setBold(False)
        font.setItalic(False)
        self.main_label1.setFont(font)
        self.main_label1.setStyleSheet("color: rgb(105, 183, 222);\n"
"font: 52pt \"Uroob\";")
        self.main_label1.setObjectName("main_label1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.main_label1)
        self.main_label2 = QtWidgets.QLabel(self.main_nameWidget)
        self.main_label2.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        self.main_label2.setFont(font)
        self.main_label2.setStyleSheet("color: rgb(105, 183, 222);\n"
"font: 50pt \"Uroob\";")
        self.main_label2.setTextFormat(QtCore.Qt.RichText)
        self.main_label2.setObjectName("main_label2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.main_label2)
        self.logo_label = QtWidgets.QLabel(self.main_nameWidget)
        self.logo_label.setMinimumSize(QtCore.QSize(100, 100))
        self.logo_label.setMaximumSize(QtCore.QSize(100, 100))
        self.logo_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap(os.path.join(os.getcwd(),"icon/logo_JINWEN.png")))
        self.logo_label.setScaledContents(True)
        self.logo_label.setObjectName("logo_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.logo_label)
        self.verticalLayout_2.addWidget(self.main_nameWidget, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.userBtn = QtWidgets.QPushButton(self.main_left)
        font = QtGui.QFont()
        font.setFamily("OpenDyslexic")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        self.userBtn.setFont(font)
        self.userBtn.setStyleSheet("QPushButton {\n"
"    font: 80 22pt \"OpenDyslexic\";\n"
"    background-color: rgb(104, 140, 183);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgba(59, 84, 120, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(127, 182, 187);\n"
"        transform: tranlateY(-2px)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(69, 69, 69);\n"
"    transfomr: translateY(0px)\n"
"}\n"
"")
        self.userBtn.setCheckable(False)
        self.userBtn.setObjectName("userBtn")
        self.verticalLayout_2.addWidget(self.userBtn)
        self.superBtn = QtWidgets.QPushButton(self.main_left)
        self.superBtn.setStyleSheet("QPushButton {\n"
"    font: 80 22pt \"OpenDyslexic\";\n"
"    background-color: rgb(104, 140, 183);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgba(59, 84, 120, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(127, 182, 187);\n"
"        transform: tranlateY(-2px)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(69, 69, 69);\n"
"    transfomr: translateY(0px)\n"
"}\n"
"")
        self.superBtn.setObjectName("superBtn")
        self.verticalLayout_2.addWidget(self.superBtn)
        self.rmBtn = QtWidgets.QPushButton(self.main_left)
        self.rmBtn.setStyleSheet("QPushButton {\n"
"    font: 80 22pt \"OpenDyslexic\";\n"
"    \n"
"    border-style: outset;\n"
"    background-color: rgb(235, 96, 90);\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgba(59, 84, 120, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"        \n"
"    background-color: rgb(245, 51, 71);\n"
"        transform: tranlateY(-2px)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(69, 69, 69);\n"
"    transfomr: translateY(0px)\n"
"}\n"
"")
        self.rmBtn.setObjectName("rmBtn")
        self.verticalLayout_2.addWidget(self.rmBtn)
        self.horizontalLayout.addWidget(self.main_left)
        self.main_right = QtWidgets.QWidget(self.mainPage)
        self.main_right.setMinimumSize(QtCore.QSize(600, 500))
        self.main_right.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.main_right.setObjectName("main_right")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_right)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.main_icon = QtWidgets.QLabel(self.main_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_icon.sizePolicy().hasHeightForWidth())
        self.main_icon.setSizePolicy(sizePolicy)
        self.main_icon.setMinimumSize(QtCore.QSize(500, 500))
        self.main_icon.setMaximumSize(QtCore.QSize(10000, 10000))
        self.main_icon.setText("")
        self.main_icon.setPixmap(QtGui.QPixmap(os.path.join(os.getcwd(),"icon/homepage-icon.png")))
        self.main_icon.setScaledContents(True)
        self.main_icon.setObjectName("main_icon")
        self.horizontalLayout_2.addWidget(self.main_icon)
        self.horizontalLayout.addWidget(self.main_right)
        self.mainStack.addWidget(self.mainPage)
        self.userPage = QtWidgets.QWidget()
        self.userPage.setObjectName("userPage")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.userPage)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.user_left = QtWidgets.QWidget(self.userPage)
        self.user_left.setMinimumSize(QtCore.QSize(300, 600))
        self.user_left.setObjectName("user_left")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.user_left)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.user_pageNameWidget = QtWidgets.QWidget(self.user_left)
        self.user_pageNameWidget.setObjectName("user_pageNameWidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.user_pageNameWidget)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.user_label1 = QtWidgets.QLabel(self.user_pageNameWidget)
        self.user_label1.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(52)
        font.setBold(False)
        font.setItalic(False)
        self.user_label1.setFont(font)
        self.user_label1.setStyleSheet("color: rgb(105, 183, 222);\n"
"font: 52pt \"Uroob\";")
        self.user_label1.setObjectName("user_label1")
        self.verticalLayout_9.addWidget(self.user_label1)
        self.user_label2 = QtWidgets.QLabel(self.user_pageNameWidget)
        self.user_label2.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        self.user_label2.setFont(font)
        self.user_label2.setStyleSheet("color: rgb(105, 183, 222);\n"
"font: 50pt \"Uroob\";")
        self.user_label2.setTextFormat(QtCore.Qt.RichText)
        self.user_label2.setObjectName("user_label2")
        self.verticalLayout_9.addWidget(self.user_label2)
        self.verticalLayout_8.addWidget(self.user_pageNameWidget, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.user_userWidget = QtWidgets.QWidget(self.user_left)
        self.user_userWidget.setObjectName("user_userWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.user_userWidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.user_perm_label = QtWidgets.QLabel(self.user_userWidget)
        self.user_perm_label.setStyleSheet("font: 80 18pt \"OpenDyslexic\";\n"
"")
        self.user_perm_label.setObjectName("user_perm_label")
        self.gridLayout_3.addWidget(self.user_perm_label, 4, 0, 1, 1)
        self.user_name_label = QtWidgets.QLabel(self.user_userWidget)
        self.user_name_label.setStyleSheet("font: 80 18pt \"OpenDyslexic\";\n"
"")
        self.user_name_label.setObjectName("user_name_label")
        self.gridLayout_3.addWidget(self.user_name_label, 0, 0, 1, 1)
        self.user_id_label = QtWidgets.QLabel(self.user_userWidget)
        self.user_id_label.setStyleSheet("font: 80 18pt \"OpenDyslexic\";\n"
"")
        self.user_id_label.setObjectName("user_id_label")
        self.gridLayout_3.addWidget(self.user_id_label, 2, 0, 1, 1)
        self.user_id_lineEdit = QtWidgets.QLineEdit(self.user_userWidget)
        self.user_id_lineEdit.setText("")
        self.user_id_lineEdit.setObjectName("user_id_lineEdit")
        self.gridLayout_3.addWidget(self.user_id_lineEdit, 3, 0, 1, 1)
        self.user_name_lineEdit = QtWidgets.QLineEdit(self.user_userWidget)
        self.user_name_lineEdit.setObjectName("user_name_lineEdit")
        self.gridLayout_3.addWidget(self.user_name_lineEdit, 1, 0, 1, 1)
        self.user_perm1 = QtWidgets.QCheckBox(self.user_userWidget)
        self.user_perm1.setStyleSheet("font: 80 18pt \"OpenDyslexic\";\n"
"")
        self.user_perm1.setIconSize(QtCore.QSize(20, 20))
        self.user_perm1.setObjectName("user_perm1")
        self.gridLayout_3.addWidget(self.user_perm1, 5, 0, 1, 1)
        self.user_perm2 = QtWidgets.QCheckBox(self.user_userWidget)
        self.user_perm2.setStyleSheet("font: 80 18pt \"OpenDyslexic\";\n"
"")
        self.user_perm2.setObjectName("user_perm2")
        self.gridLayout_3.addWidget(self.user_perm2, 5, 1, 1, 1)
        self.verticalLayout_8.addWidget(self.user_userWidget)
        self.user_leftBtnWidget = QtWidgets.QWidget(self.user_left)
        self.user_leftBtnWidget.setObjectName("user_leftBtnWidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.user_leftBtnWidget)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.user_takeBtn = QtWidgets.QPushButton(self.user_leftBtnWidget)
        font = QtGui.QFont()
        font.setFamily("OpenDyslexic")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        self.user_takeBtn.setFont(font)
        self.user_takeBtn.setStyleSheet("QPushButton {\n"
"    font: 80 22pt \"OpenDyslexic\";\n"
"    background-color: rgb(104, 140, 183);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgba(59, 84, 120, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(127, 182, 187);\n"
"        transform: tranlateY(-2px)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(69, 69, 69);\n"
"    transfomr: translateY(0px)\n"
"}\n"
"")
        self.user_takeBtn.setCheckable(False)
        self.user_takeBtn.setObjectName("user_takeBtn")
        self.verticalLayout_10.addWidget(self.user_takeBtn)
        self.user_homeBtn = QtWidgets.QPushButton(self.user_leftBtnWidget)
        font = QtGui.QFont()
        font.setFamily("OpenDyslexic")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        self.user_homeBtn.setFont(font)
        self.user_homeBtn.setStyleSheet("QPushButton {\n"
"    font: 80 22pt \"OpenDyslexic\";\n"
"    background-color: rgb(104, 140, 183);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgba(59, 84, 120, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(127, 182, 187);\n"
"        transform: tranlateY(-2px)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(69, 69, 69);\n"
"    transfomr: translateY(0px)\n"
"}\n"
"")
        self.user_homeBtn.setCheckable(False)
        self.user_homeBtn.setObjectName("user_homeBtn")
        self.verticalLayout_10.addWidget(self.user_homeBtn, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_8.addWidget(self.user_leftBtnWidget, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_5.addWidget(self.user_left)
        self.user_right = QtWidgets.QWidget(self.userPage)
        self.user_right.setMinimumSize(QtCore.QSize(600, 600))
        self.user_right.setObjectName("user_right")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.user_right)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.user_WC = QtWidgets.QFrame(self.user_right)
        self.user_WC.setMinimumSize(QtCore.QSize(500, 500))
        self.user_WC.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.user_WC.setFrameShadow(QtWidgets.QFrame.Raised)
        self.user_WC.setObjectName("user_WC")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.user_WC)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.user_labelWC = QtWidgets.QLabel(self.user_WC)
        self.user_labelWC.setText("")
        self.user_labelWC.setObjectName("user_labelWC")
        self.horizontalLayout_9.addWidget(self.user_labelWC)
        self.verticalLayout_7.addWidget(self.user_WC)
        self.user_rightBtnWiget = QtWidgets.QWidget(self.user_right)
        self.user_rightBtnWiget.setObjectName("user_rightBtnWiget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.user_rightBtnWiget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.user_retakeBtn = QtWidgets.QPushButton(self.user_rightBtnWiget)
        font = QtGui.QFont()
        font.setFamily("OpenDyslexic")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        self.user_retakeBtn.setFont(font)
        self.user_retakeBtn.setStyleSheet("QPushButton {\n"
"    font: 80 22pt \"OpenDyslexic\";\n"
"    background-color: rgb(199,22,43);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgba(59, 84, 120, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"        \n"
"    background-color: rgb(245, 51, 71);\n"
"        transform: tranlateY(-2px)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(69, 69, 69);\n"
"    transfomr: translateY(0px)\n"
"}\n"
"")
        self.user_retakeBtn.setCheckable(False)
        self.user_retakeBtn.setObjectName("user_retakeBtn")
        self.horizontalLayout_4.addWidget(self.user_retakeBtn)
        self.user_okBtn = QtWidgets.QPushButton(self.user_rightBtnWiget)
        font = QtGui.QFont()
        font.setFamily("OpenDyslexic")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        self.user_okBtn.setFont(font)
        self.user_okBtn.setStyleSheet("QPushButton {\n"
"    font: 80 22pt \"OpenDyslexic\";\n"
"    background-color: rgb(15,153,32);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgba(59, 84, 120, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(104, 211, 70);\n"
"        transform: tranlateY(-2px)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(69, 69, 69);\n"
"    transfomr: translateY(0px)\n"
"}\n"
"\n"
"")
        self.user_okBtn.setCheckable(False)
        self.user_okBtn.setObjectName("user_okBtn")
        self.horizontalLayout_4.addWidget(self.user_okBtn)
        self.verticalLayout_7.addWidget(self.user_rightBtnWiget, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_5.addWidget(self.user_right)
        self.mainStack.addWidget(self.userPage)
        self.superPage = QtWidgets.QWidget()
        self.superPage.setObjectName("superPage")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.superPage)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.super_left = QtWidgets.QWidget(self.superPage)
        self.super_left.setMinimumSize(QtCore.QSize(300, 600))
        self.super_left.setObjectName("super_left")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.super_left)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.super_nameWidget = QtWidgets.QWidget(self.super_left)
        self.super_nameWidget.setObjectName("super_nameWidget")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.super_nameWidget)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.super_label1 = QtWidgets.QLabel(self.super_nameWidget)
        self.super_label1.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(52)
        font.setBold(False)
        font.setItalic(False)
        self.super_label1.setFont(font)
        self.super_label1.setStyleSheet("color: rgb(105, 183, 222);\n"
"font: 52pt \"Uroob\";")
        self.super_label1.setObjectName("super_label1")
        self.verticalLayout_17.addWidget(self.super_label1)
        self.super_label2 = QtWidgets.QLabel(self.super_nameWidget)
        self.super_label2.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        self.super_label2.setFont(font)
        self.super_label2.setStyleSheet("color: rgb(105, 183, 222);\n"
"font: 50pt \"Uroob\";")
        self.super_label2.setTextFormat(QtCore.Qt.RichText)
        self.super_label2.setObjectName("super_label2")
        self.verticalLayout_17.addWidget(self.super_label2)
        self.verticalLayout_16.addWidget(self.super_nameWidget, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.super_userWidget = QtWidgets.QWidget(self.super_left)
        self.super_userWidget.setObjectName("super_userWidget")
        self.formLayout_4 = QtWidgets.QFormLayout(self.super_userWidget)
        self.formLayout_4.setObjectName("formLayout_4")
        self.super_name_label = QtWidgets.QLabel(self.super_userWidget)
        self.super_name_label.setStyleSheet("font: 80 18pt \"OpenDyslexic\";\n"
"")
        self.super_name_label.setObjectName("super_name_label")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.super_name_label)
        self.super_name_lineEdit = QtWidgets.QLineEdit(self.super_userWidget)
        self.super_name_lineEdit.setObjectName("super_name_lineEdit")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.super_name_lineEdit)
        self.super_id_label = QtWidgets.QLabel(self.super_userWidget)
        self.super_id_label.setStyleSheet("font: 80 18pt \"OpenDyslexic\";\n"
"")
        self.super_id_label.setObjectName("super_id_label")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.super_id_label)
        self.super_id_lineEdit = QtWidgets.QLineEdit(self.super_userWidget)
        self.super_id_lineEdit.setText("")
        self.super_id_lineEdit.setObjectName("super_id_lineEdit")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.super_id_lineEdit)
        self.supervisor_label_3 = QtWidgets.QLabel(self.super_userWidget)
        self.supervisor_label_3.setStyleSheet("font: 80 18pt \"OpenDyslexic\";\n"
"")
        self.supervisor_label_3.setObjectName("supervisor_label_3")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.supervisor_label_3)
        self.supervisor_lineEdit_3 = QtWidgets.QLineEdit(self.super_userWidget)
        self.supervisor_lineEdit_3.setText("")
        self.supervisor_lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.supervisor_lineEdit_3.setObjectName("supervisor_lineEdit_3")
        self.formLayout_4.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.supervisor_lineEdit_3)
        self.verticalLayout_16.addWidget(self.super_userWidget, 0, QtCore.Qt.AlignTop)
        self.super_leftBtnWidget = QtWidgets.QWidget(self.super_left)
        self.super_leftBtnWidget.setObjectName("super_leftBtnWidget")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.super_leftBtnWidget)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.super_takeBtn = QtWidgets.QPushButton(self.super_leftBtnWidget)
        font = QtGui.QFont()
        font.setFamily("OpenDyslexic")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        self.super_takeBtn.setFont(font)
        self.super_takeBtn.setMouseTracking(True)
        self.super_takeBtn.setStyleSheet("QPushButton {\n"
"    font: 80 22pt \"OpenDyslexic\";\n"
"    background-color: rgb(104, 140, 183);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgba(59, 84, 120, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(127, 182, 187);\n"
"        transform: tranlateY(-2px)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(69, 69, 69);\n"
"    transfomr: translateY(0px)\n"
"}\n"
"")
        self.super_takeBtn.setCheckable(False)
        self.super_takeBtn.setObjectName("super_takeBtn")
        self.verticalLayout_18.addWidget(self.super_takeBtn)
        self.super_homeBtn = QtWidgets.QPushButton(self.super_leftBtnWidget)
        font = QtGui.QFont()
        font.setFamily("OpenDyslexic")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        self.super_homeBtn.setFont(font)
        self.super_homeBtn.setMouseTracking(True)
        self.super_homeBtn.setStyleSheet("QPushButton {\n"
"    font: 80 22pt \"OpenDyslexic\";\n"
"    background-color: rgb(104, 140, 183);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgba(59, 84, 120, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(127, 182, 187);\n"
"        transform: tranlateY(-2px)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(69, 69, 69);\n"
"    transfomr: translateY(0px)\n"
"}\n"
"")
        self.super_homeBtn.setCheckable(False)
        self.super_homeBtn.setObjectName("super_homeBtn")
        self.verticalLayout_18.addWidget(self.super_homeBtn, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_16.addWidget(self.super_leftBtnWidget, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_8.addWidget(self.super_left)
        self.super_right = QtWidgets.QWidget(self.superPage)
        self.super_right.setMinimumSize(QtCore.QSize(600, 600))
        self.super_right.setObjectName("super_right")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.super_right)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.super_WC = QtWidgets.QFrame(self.super_right)
        self.super_WC.setMinimumSize(QtCore.QSize(500, 500))
        self.super_WC.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.super_WC.setFrameShadow(QtWidgets.QFrame.Raised)
        self.super_WC.setObjectName("super_WC")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.super_WC)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.super_labelWC = QtWidgets.QLabel(self.super_WC)
        self.super_labelWC.setText("")
        self.super_labelWC.setObjectName("super_labelWC")
        self.horizontalLayout_6.addWidget(self.super_labelWC)
        self.verticalLayout_15.addWidget(self.super_WC)
        self.super_rightBtnWidget = QtWidgets.QWidget(self.super_right)
        self.super_rightBtnWidget.setObjectName("super_rightBtnWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.super_rightBtnWidget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.super_retakeBtn = QtWidgets.QPushButton(self.super_rightBtnWidget)
        font = QtGui.QFont()
        font.setFamily("OpenDyslexic")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        self.super_retakeBtn.setFont(font)
        self.super_retakeBtn.setStyleSheet("QPushButton {\n"
"    font: 80 22pt \"OpenDyslexic\";\n"
"    background-color: rgb(199,22,43);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgba(59, 84, 120, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"        \n"
"    background-color: rgb(245, 51, 71);\n"
"        transform: tranlateY(-2px)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(69, 69, 69);\n"
"    transfomr: translateY(0px)\n"
"}\n"
"")
        self.super_retakeBtn.setCheckable(False)
        self.super_retakeBtn.setObjectName("super_retakeBtn")
        self.horizontalLayout_7.addWidget(self.super_retakeBtn)
        self.super_okBtn = QtWidgets.QPushButton(self.super_rightBtnWidget)
        font = QtGui.QFont()
        font.setFamily("OpenDyslexic")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        self.super_okBtn.setFont(font)
        self.super_okBtn.setStyleSheet("QPushButton {\n"
"    font: 80 22pt \"OpenDyslexic\";\n"
"    background-color: rgb(15,153,32);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgba(59, 84, 120, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(104, 211, 70);\n"
"        transform: tranlateY(-2px)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(69, 69, 69);\n"
"    transfomr: translateY(0px)\n"
"}\n"
"\n"
"")
        self.super_okBtn.setCheckable(False)
        self.super_okBtn.setObjectName("super_okBtn")
        self.horizontalLayout_7.addWidget(self.super_okBtn)
        self.verticalLayout_15.addWidget(self.super_rightBtnWidget, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_8.addWidget(self.super_right)
        self.mainStack.addWidget(self.superPage)
        self.removePage = QtWidgets.QWidget()
        self.removePage.setMaximumSize(QtCore.QSize(600, 16777215))
        self.removePage.setObjectName("removePage")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.removePage)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.remStack = QtWidgets.QStackedWidget(self.removePage)
        self.remStack.setMaximumSize(QtCore.QSize(600, 16777215))
        self.remStack.setObjectName("remStack")
        self.rmPage = QtWidgets.QWidget()
        self.rmPage.setObjectName("rmPage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.rmPage)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.rm_labelWidget = QtWidgets.QWidget(self.rmPage)
        self.rm_labelWidget.setObjectName("rm_labelWidget")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.rm_labelWidget)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.rm_label1 = QtWidgets.QLabel(self.rm_labelWidget)
        self.rm_label1.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(52)
        font.setBold(False)
        font.setItalic(False)
        self.rm_label1.setFont(font)
        self.rm_label1.setStyleSheet("color: rgb(105, 183, 222);\n"
"font: 52pt \"Uroob\";")
        self.rm_label1.setObjectName("rm_label1")
        self.verticalLayout_20.addWidget(self.rm_label1)
        self.rm_label2 = QtWidgets.QLabel(self.rm_labelWidget)
        self.rm_label2.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        self.rm_label2.setFont(font)
        self.rm_label2.setStyleSheet("color: rgb(105, 183, 222);\n"
"font: 50pt \"Uroob\";")
        self.rm_label2.setTextFormat(QtCore.Qt.RichText)
        self.rm_label2.setObjectName("rm_label2")
        self.verticalLayout_20.addWidget(self.rm_label2)
        self.verticalLayout_5.addWidget(self.rm_labelWidget, 0, QtCore.Qt.AlignVCenter)
        self.rm_labelWidget2 = QtWidgets.QWidget(self.rmPage)
        self.rm_labelWidget2.setMinimumSize(QtCore.QSize(0, 0))
        self.rm_labelWidget2.setMaximumSize(QtCore.QSize(10000, 10000))
        self.rm_labelWidget2.setObjectName("rm_labelWidget2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.rm_labelWidget2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.rm_label3 = QtWidgets.QLabel(self.rm_labelWidget2)
        self.rm_label3.setStyleSheet("font: 80 18pt \"OpenDyslexic\";\n"
"")
        self.rm_label3.setObjectName("rm_label3")
        self.verticalLayout_11.addWidget(self.rm_label3)
        self.rm_label3_2 = QtWidgets.QLabel(self.rm_labelWidget2)
        self.rm_label3_2.setStyleSheet("font: 80 18pt \"OpenDyslexic\";\n"
"")
        self.rm_label3_2.setObjectName("rm_label3_2")
        self.verticalLayout_11.addWidget(self.rm_label3_2)
        self.rm_label4 = QtWidgets.QLabel(self.rm_labelWidget2)
        self.rm_label4.setStyleSheet("font: 80 18pt \"OpenDyslexic\";\n"
"")
        self.rm_label4.setObjectName("rm_label4")
        self.verticalLayout_11.addWidget(self.rm_label4)
        self.verticalLayout_5.addWidget(self.rm_labelWidget2)
        self.rm_userWidget = QtWidgets.QWidget(self.rmPage)
        self.rm_userWidget.setObjectName("rm_userWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.rm_userWidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.rm_name_label = QtWidgets.QLabel(self.rm_userWidget)
        self.rm_name_label.setStyleSheet("font: 80 26pt \"OpenDyslexic\";\n"
"")
        self.rm_name_label.setObjectName("rm_name_label")
        self.verticalLayout_6.addWidget(self.rm_name_label)
        self.rm_name_lineEdit = QtWidgets.QLineEdit(self.rm_userWidget)
        self.rm_name_lineEdit.setClearButtonEnabled(True)
        self.rm_name_lineEdit.setObjectName("rm_name_lineEdit")
        self.verticalLayout_6.addWidget(self.rm_name_lineEdit)
        self.verticalLayout_5.addWidget(self.rm_userWidget, 0, QtCore.Qt.AlignBottom)
        self.buttonWidget = QtWidgets.QWidget(self.rmPage)
        self.buttonWidget.setObjectName("buttonWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.buttonWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rm_homeBtn = QtWidgets.QPushButton(self.buttonWidget)
        font = QtGui.QFont()
        font.setFamily("OpenDyslexic")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        self.rm_homeBtn.setFont(font)
        self.rm_homeBtn.setStyleSheet("QPushButton {\n"
"    font: 80 22pt \"OpenDyslexic\";\n"
"    background-color: rgb(104, 140, 183);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgba(59, 84, 120, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(127, 182, 187);\n"
"        transform: tranlateY(-2px)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(69, 69, 69);\n"
"    transfomr: translateY(0px)\n"
"}\n"
"")
        self.rm_homeBtn.setCheckable(False)
        self.rm_homeBtn.setObjectName("rm_homeBtn")
        self.gridLayout_2.addWidget(self.rm_homeBtn, 0, 0, 1, 1)
        self.rm_rmBtn = QtWidgets.QPushButton(self.buttonWidget)
        self.rm_rmBtn.setStyleSheet("QPushButton {\n"
"    font: 80 22pt \"OpenDyslexic\";\n"
"    \n"
"    border-style: outset;\n"
"    background-color: rgb(235, 96, 90);\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgba(59, 84, 120, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"        \n"
"    background-color: rgb(245, 51, 71);\n"
"        transform: tranlateY(-2px)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(69, 69, 69);\n"
"    transfomr: translateY(0px)\n"
"}\n"
"")
        self.rm_rmBtn.setObjectName("rm_rmBtn")
        self.gridLayout_2.addWidget(self.rm_rmBtn, 0, 1, 1, 1)
        self.rm_rmAllBtn = QtWidgets.QPushButton(self.buttonWidget)
        self.rm_rmAllBtn.setStyleSheet("QPushButton {\n"
"    font: 80 22pt \"OpenDyslexic\";\n"
"    \n"
"    border-style: outset;\n"
"    background-color: rgb(235, 96, 90);\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgba(59, 84, 120, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"        \n"
"    background-color: rgb(245, 51, 71);\n"
"        transform: tranlateY(-2px)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(69, 69, 69);\n"
"    transfomr: translateY(0px)\n"
"}\n"
"")
        self.rm_rmAllBtn.setObjectName("rm_rmAllBtn")
        self.gridLayout_2.addWidget(self.rm_rmAllBtn, 1, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.buttonWidget)
        self.remStack.addWidget(self.rmPage)
        self.confirmPage = QtWidgets.QWidget()
        self.confirmPage.setObjectName("confirmPage")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.confirmPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cf_labelwidget = QtWidgets.QWidget(self.confirmPage)
        self.cf_labelwidget.setObjectName("cf_labelwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.cf_labelwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.cf_label1 = QtWidgets.QLabel(self.cf_labelwidget)
        self.cf_label1.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(52)
        font.setBold(False)
        font.setItalic(False)
        self.cf_label1.setFont(font)
        self.cf_label1.setStyleSheet("color: rgb(105, 183, 222);\n"
"font: 52pt \"Uroob\";")
        self.cf_label1.setObjectName("cf_label1")
        self.gridLayout.addWidget(self.cf_label1, 0, 0, 1, 1)
        self.cf_confirmBtn = QtWidgets.QPushButton(self.cf_labelwidget)
        self.cf_confirmBtn.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("OpenDyslexic")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        self.cf_confirmBtn.setFont(font)
        self.cf_confirmBtn.setStyleSheet("QPushButton {\n"
"    font: 80 18pt \"OpenDyslexic\";\n"
"    background-color: rgb(104, 140, 183);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgba(59, 84, 120, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(127, 182, 187);\n"
"        transform: tranlateY(-2px)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(69, 69, 69);\n"
"    transfomr: translateY(0px)\n"
"}\n"
"")
        self.cf_confirmBtn.setCheckable(False)
        self.cf_confirmBtn.setObjectName("cf_confirmBtn")
        self.gridLayout.addWidget(self.cf_confirmBtn, 0, 1, 1, 1)
        self.cf_label2 = QtWidgets.QLabel(self.cf_labelwidget)
        self.cf_label2.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        self.cf_label2.setFont(font)
        self.cf_label2.setStyleSheet("color: rgb(105, 183, 222);\n"
"font: 50pt \"Uroob\";")
        self.cf_label2.setTextFormat(QtCore.Qt.RichText)
        self.cf_label2.setObjectName("cf_label2")
        self.gridLayout.addWidget(self.cf_label2, 1, 0, 1, 1)
        self.cf_homeBtn = QtWidgets.QPushButton(self.cf_labelwidget)
        self.cf_homeBtn.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setFamily("OpenDyslexic")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setKerning(True)
        self.cf_homeBtn.setFont(font)
        self.cf_homeBtn.setStyleSheet("QPushButton {\n"
"    font: 80 18pt \"OpenDyslexic\";\n"
"    background-color: rgb(104, 140, 183);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgba(59, 84, 120, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(127, 182, 187);\n"
"        transform: tranlateY(-2px)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(69, 69, 69);\n"
"    transfomr: translateY(0px)\n"
"}\n"
"")
        self.cf_homeBtn.setCheckable(False)
        self.cf_homeBtn.setObjectName("cf_homeBtn")
        self.gridLayout.addWidget(self.cf_homeBtn, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.cf_labelwidget)
        self.confirm_WC = QtWidgets.QFrame(self.confirmPage)
        self.confirm_WC.setMinimumSize(QtCore.QSize(500, 500))
        self.confirm_WC.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.confirm_WC.setFrameShadow(QtWidgets.QFrame.Raised)
        self.confirm_WC.setObjectName("confirm_WC")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.confirm_WC)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cf_labelWC = QtWidgets.QLabel(self.confirm_WC)
        self.cf_labelWC.setMinimumSize(QtCore.QSize(550, 550))
        self.cf_labelWC.setText("")
        self.cf_labelWC.setObjectName("cf_labelWC")
        self.horizontalLayout_3.addWidget(self.cf_labelWC)
        self.verticalLayout.addWidget(self.confirm_WC)
        self.remStack.addWidget(self.confirmPage)
        self.verticalLayout_4.addWidget(self.remStack)
        self.mainStack.addWidget(self.removePage)
        self.horizontalLayout_11.addWidget(self.mainStack)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.mainStack.setCurrentIndex(1)
        self.remStack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.main_label1.setText(_translate("MainWindow", "Face"))
        self.main_label2.setText(_translate("MainWindow", "Recognition"))
        self.userBtn.setText(_translate("MainWindow", "Regisiter User"))
        self.superBtn.setText(_translate("MainWindow", "Add supervisor"))
        self.rmBtn.setText(_translate("MainWindow", "Remove User"))
        self.user_label1.setText(_translate("MainWindow", "Regisiter"))
        self.user_label2.setText(_translate("MainWindow", "User"))
        self.user_perm_label.setText(_translate("MainWindow", "Permissions "))
        self.user_name_label.setText(_translate("MainWindow", "Name"))
        self.user_id_label.setText(_translate("MainWindow", "ID"))
        self.user_perm1.setText(_translate("MainWindow", "Entrance"))
        self.user_perm2.setText(_translate("MainWindow", "Metting Room"))
        self.user_takeBtn.setText(_translate("MainWindow", "Take a photo"))
        self.user_homeBtn.setText(_translate("MainWindow", "Main page"))
        self.user_retakeBtn.setText(_translate("MainWindow", "Retake"))
        self.user_okBtn.setText(_translate("MainWindow", "OK"))
        self.super_label1.setText(_translate("MainWindow", "Add"))
        self.super_label2.setText(_translate("MainWindow", "Supervisor"))
        self.super_name_label.setText(_translate("MainWindow", "Name"))
        self.super_id_label.setText(_translate("MainWindow", "ID"))
        self.supervisor_label_3.setText(_translate("MainWindow", "Supervisor Code"))
        self.super_takeBtn.setText(_translate("MainWindow", "Take a photo"))
        self.super_homeBtn.setText(_translate("MainWindow", "Main page"))
        self.super_retakeBtn.setText(_translate("MainWindow", "Retake"))
        self.super_okBtn.setText(_translate("MainWindow", "OK"))
        self.rm_label1.setText(_translate("MainWindow", "Remove"))
        self.rm_label2.setText(_translate("MainWindow", "User"))
        self.rm_label3.setText(_translate("MainWindow", "If you are supervisor,  you can enter the name you want to remove."))
        self.rm_label3_2.setText(_translate("MainWindow", "Or,  you can remove all of user including yourself."))
        self.rm_label4.setText(_translate("MainWindow", "If not,  you can only remove your own information."))
        self.rm_name_label.setText(_translate("MainWindow", "Name"))
        self.rm_homeBtn.setText(_translate("MainWindow", "Main page"))
        self.rm_rmBtn.setText(_translate("MainWindow", "Remove User"))
        self.rm_rmAllBtn.setText(_translate("MainWindow", "Remove all user"))
        self.cf_label1.setText(_translate("MainWindow", "Confirm"))
        self.cf_confirmBtn.setText(_translate("MainWindow", "Confirm"))
        self.cf_label2.setText(_translate("MainWindow", "Identity"))
        self.cf_homeBtn.setText(_translate("MainWindow", "Main page"))
