# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/AddSupervisor.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RegistierWindow(object):
    def setupUi(self, RegistierWindow):
        RegistierWindow.setObjectName("RegistierWindow")
        RegistierWindow.resize(924, 600)
        RegistierWindow.setMinimumSize(QtCore.QSize(0, 600))
        self.centralwidget = QtWidgets.QWidget(RegistierWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Left = QtWidgets.QWidget(self.centralwidget)
        self.Left.setMinimumSize(QtCore.QSize(300, 600))
        self.Left.setObjectName("Left")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Left)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pageNameWidget = QtWidgets.QWidget(self.Left)
        self.pageNameWidget.setObjectName("pageNameWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pageNameWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_1 = QtWidgets.QLabel(self.pageNameWidget)
        self.label_1.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(52)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("color: rgb(105, 183, 222);\n"
"font: 52pt \"Uroob\";")
        self.label_1.setObjectName("label_1")
        self.verticalLayout_2.addWidget(self.label_1)
        self.label_2 = QtWidgets.QLabel(self.pageNameWidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(105, 183, 222);\n"
"font: 50pt \"Uroob\";")
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.pageNameWidget, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.userWidget = QtWidgets.QWidget(self.Left)
        self.userWidget.setObjectName("userWidget")
        self.formLayout = QtWidgets.QFormLayout(self.userWidget)
        self.formLayout.setObjectName("formLayout")
        self.name_label = QtWidgets.QLabel(self.userWidget)
        self.name_label.setStyleSheet("font: 80 18pt \"OpenDyslexic\";\n"
"")
        self.name_label.setObjectName("name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.name_label)
        self.name_lineEdit = QtWidgets.QLineEdit(self.userWidget)
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.name_lineEdit)
        self.id_label = QtWidgets.QLabel(self.userWidget)
        self.id_label.setStyleSheet("font: 80 18pt \"OpenDyslexic\";\n"
"")
        self.id_label.setObjectName("id_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.id_label)
        self.id_lineEdit = QtWidgets.QLineEdit(self.userWidget)
        self.id_lineEdit.setText("")
        self.id_lineEdit.setObjectName("id_lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.id_lineEdit)
        self.supervisor_label = QtWidgets.QLabel(self.userWidget)
        self.supervisor_label.setStyleSheet("font: 80 18pt \"OpenDyslexic\";\n"
"")
        self.supervisor_label.setObjectName("supervisor_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.supervisor_label)
        self.supervisor_lineEdit = QtWidgets.QLineEdit(self.userWidget)
        self.supervisor_lineEdit.setText("")
        self.supervisor_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.supervisor_lineEdit.setObjectName("supervisor_lineEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.supervisor_lineEdit)
        self.verticalLayout.addWidget(self.userWidget, 0, QtCore.Qt.AlignTop)
        self.leftBtnWidget = QtWidgets.QWidget(self.Left)
        self.leftBtnWidget.setObjectName("leftBtnWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.leftBtnWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.takeButton = QtWidgets.QPushButton(self.leftBtnWidget)
        font = QtGui.QFont()
        font.setFamily("OpenDyslexic")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        font.setKerning(True)
        self.takeButton.setFont(font)
        self.takeButton.setMouseTracking(True)
        self.takeButton.setStyleSheet("QPushButton {\n"
"    font: 80 22pt \"OpenDyslexic\";\n"
"    background-color: rgb(104, 140, 183);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgba(59, 84, 120, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(127, 182, 187);\n"
"        transform: tranlateY(-2px)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(69, 69, 69);\n"
"    transfomr: translateY(0px)\n"
"}\n"
"")
        self.takeButton.setCheckable(False)
        self.takeButton.setObjectName("takeButton")
        self.verticalLayout_3.addWidget(self.takeButton)
        self.returnButton = QtWidgets.QPushButton(self.leftBtnWidget)
        font = QtGui.QFont()
        font.setFamily("OpenDyslexic")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        font.setKerning(True)
        self.returnButton.setFont(font)
        self.returnButton.setMouseTracking(True)
        self.returnButton.setStyleSheet("QPushButton {\n"
"    font: 80 22pt \"OpenDyslexic\";\n"
"    background-color: rgb(104, 140, 183);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgba(59, 84, 120, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(127, 182, 187);\n"
"        transform: tranlateY(-2px)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(69, 69, 69);\n"
"    transfomr: translateY(0px)\n"
"}\n"
"")
        self.returnButton.setCheckable(False)
        self.returnButton.setObjectName("returnButton")
        self.verticalLayout_3.addWidget(self.returnButton, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.leftBtnWidget, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.Left)
        self.right = QtWidgets.QWidget(self.centralwidget)
        self.right.setMinimumSize(QtCore.QSize(600, 600))
        self.right.setObjectName("right")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.right)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.webcamFrame = QtWidgets.QFrame(self.right)
        self.webcamFrame.setMinimumSize(QtCore.QSize(500, 500))
        self.webcamFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.webcamFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.webcamFrame.setObjectName("webcamFrame")
        self.verticalLayout_4.addWidget(self.webcamFrame)
        self.rightBtnWidget = QtWidgets.QWidget(self.right)
        self.rightBtnWidget.setObjectName("rightBtnWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.rightBtnWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.retakeButton = QtWidgets.QPushButton(self.rightBtnWidget)
        font = QtGui.QFont()
        font.setFamily("OpenDyslexic")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        font.setKerning(True)
        self.retakeButton.setFont(font)
        self.retakeButton.setStyleSheet("QPushButton {\n"
"    font: 80 22pt \"OpenDyslexic\";\n"
"    background-color: rgb(199,22,43);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgba(59, 84, 120, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"        \n"
"    background-color: rgb(245, 51, 71);\n"
"        transform: tranlateY(-2px)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(69, 69, 69);\n"
"    transfomr: translateY(0px)\n"
"}\n"
"")
        self.retakeButton.setCheckable(False)
        self.retakeButton.setObjectName("retakeButton")
        self.horizontalLayout_2.addWidget(self.retakeButton)
        self.okButton = QtWidgets.QPushButton(self.rightBtnWidget)
        font = QtGui.QFont()
        font.setFamily("OpenDyslexic")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        font.setKerning(True)
        self.okButton.setFont(font)
        self.okButton.setStyleSheet("QPushButton {\n"
"    font: 80 22pt \"OpenDyslexic\";\n"
"    background-color: rgb(15,153,32);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgba(59, 84, 120, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(104, 211, 70);\n"
"        transform: tranlateY(-2px)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(69, 69, 69);\n"
"    transfomr: translateY(0px)\n"
"}\n"
"\n"
"")
        self.okButton.setCheckable(False)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout_2.addWidget(self.okButton)
        self.verticalLayout_4.addWidget(self.rightBtnWidget, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout.addWidget(self.right)
        RegistierWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RegistierWindow)
        QtCore.QMetaObject.connectSlotsByName(RegistierWindow)

    def retranslateUi(self, RegistierWindow):
        _translate = QtCore.QCoreApplication.translate
        RegistierWindow.setWindowTitle(_translate("RegistierWindow", "MainWindow"))
        self.label_1.setText(_translate("RegistierWindow", "Add"))
        self.label_2.setText(_translate("RegistierWindow", "Supervisor"))
        self.name_label.setText(_translate("RegistierWindow", "Name"))
        self.id_label.setText(_translate("RegistierWindow", "ID"))
        self.supervisor_label.setText(_translate("RegistierWindow", "Supervisor Code"))
        self.takeButton.setText(_translate("RegistierWindow", "Take a photo"))
        self.returnButton.setText(_translate("RegistierWindow", "Main page"))
        self.retakeButton.setText(_translate("RegistierWindow", "Retake"))
        self.okButton.setText(_translate("RegistierWindow", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegistierWindow = QtWidgets.QMainWindow()
    ui = Ui_RegistierWindow()
    ui.setupUi(RegistierWindow)
    RegistierWindow.show()
    sys.exit(app.exec_())
