# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os,sys
from PyQt5 import QtCore, QtGui, QtWidgets
from addUser import Ui_RegistierWindow as window_addUser



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(924, 600)
        MainWindow.setMinimumSize(QtCore.QSize(0, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Left = QtWidgets.QWidget(self.centralwidget)
        self.Left.setMinimumSize(QtCore.QSize(300, 500))
        self.Left.setObjectName("Left")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Left)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.nameWidget = QtWidgets.QWidget(self.Left)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nameWidget.setFont(font)
        self.nameWidget.setObjectName("nameWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.nameWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_1 = QtWidgets.QLabel(self.nameWidget)
        self.label_1.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(52)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("color: rgb(105, 183, 222);\n"
"font: 52pt \"Uroob\";")
        self.label_1.setObjectName("label_1")
        self.verticalLayout_3.addWidget(self.label_1, 0, QtCore.Qt.AlignLeft)
        self.label_2 = QtWidgets.QLabel(self.nameWidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(105, 183, 222);\n"
"font: 50pt \"Uroob\";")
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.nameWidget, 0, QtCore.Qt.AlignTop)
        self.regisiterButton = QtWidgets.QPushButton(self.Left)
        font = QtGui.QFont()
        font.setFamily("OpenDyslexic")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        font.setKerning(True)
        self.regisiterButton.setFont(font)
        self.regisiterButton.setStyleSheet("QPushButton {\n"
"    font: 80 22pt \"OpenDyslexic\";\n"
"    background-color: rgb(104, 140, 183);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgba(59, 84, 120, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(127, 182, 187);\n"
"        transform: tranlateY(-2px)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(69, 69, 69);\n"
"    transfomr: translateY(0px)\n"
"}\n"
"")
        self.regisiterButton.setCheckable(False)
        self.regisiterButton.setObjectName("regisiterButton")
        self.verticalLayout_2.addWidget(self.regisiterButton)
        self.addSupurButton = QtWidgets.QPushButton(self.Left)
        self.addSupurButton.setStyleSheet("QPushButton {\n"
"    font: 80 22pt \"OpenDyslexic\";\n"
"    background-color: rgb(104, 140, 183);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgba(59, 84, 120, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(127, 182, 187);\n"
"        transform: tranlateY(-2px)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(69, 69, 69);\n"
"    transfomr: translateY(0px)\n"
"}\n"
"")
        self.addSupurButton.setObjectName("addSupurButton")
        self.verticalLayout_2.addWidget(self.addSupurButton)
        self.removeButton = QtWidgets.QPushButton(self.Left)
        self.removeButton.setStyleSheet("QPushButton {\n"
"    font: 80 22pt \"OpenDyslexic\";\n"
"    \n"
"    border-style: outset;\n"
"    background-color: rgb(235, 96, 90);\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgba(59, 84, 120, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"        \n"
"    background-color: rgb(245, 51, 71);\n"
"        transform: tranlateY(-2px)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(69, 69, 69);\n"
"    transfomr: translateY(0px)\n"
"}\n"
"")
        self.removeButton.setObjectName("removeButton")
        self.verticalLayout_2.addWidget(self.removeButton)
        self.horizontalLayout.addWidget(self.Left)
        self.right = QtWidgets.QWidget(self.centralwidget)
        self.right.setMinimumSize(QtCore.QSize(600, 500))
        self.right.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.right.setObjectName("right")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.right)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.icon = QtWidgets.QLabel(self.right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon.sizePolicy().hasHeightForWidth())
        self.icon.setSizePolicy(sizePolicy)
        self.icon.setMinimumSize(QtCore.QSize(500, 500))
        self.icon.setMaximumSize(QtCore.QSize(10000, 10000))
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap(os.path.join(os.getcwd(),"..","icon/homepage-icon.png")))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.horizontalLayout_2.addWidget(self.icon)
        self.horizontalLayout.addWidget(self.right, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # #button clicked
        # self.regisiterButton.clicked.connect(self.toRegisterWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_1.setText(_translate("MainWindow", "Face"))
        self.label_2.setText(_translate("MainWindow", "Recognition"))
        self.regisiterButton.setText(_translate("MainWindow", "Regisiter User"))
        self.addSupurButton.setText(_translate("MainWindow", "Add supervisor"))
        self.removeButton.setText(_translate("MainWindow", "Remove User"))





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
