# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/RemoveUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(318, 640)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.center = QtWidgets.QWidget(self.centralwidget)
        self.center.setMinimumSize(QtCore.QSize(300, 600))
        self.center.setObjectName("center")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.center)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelWidget = QtWidgets.QWidget(self.center)
        self.labelWidget.setObjectName("labelWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.labelWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_1 = QtWidgets.QLabel(self.labelWidget)
        self.label_1.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(52)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("color: rgb(105, 183, 222);\n"
"font: 52pt \"Uroob\";")
        self.label_1.setObjectName("label_1")
        self.verticalLayout_2.addWidget(self.label_1)
        self.label_2 = QtWidgets.QLabel(self.labelWidget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Uroob")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(105, 183, 222);\n"
"font: 50pt \"Uroob\";")
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.labelWidget, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.userWidget = QtWidgets.QWidget(self.center)
        self.userWidget.setObjectName("userWidget")
        self.formLayout = QtWidgets.QFormLayout(self.userWidget)
        self.formLayout.setObjectName("formLayout")
        self.name_label = QtWidgets.QLabel(self.userWidget)
        self.name_label.setStyleSheet("font: 80 18pt \"OpenDyslexic\";\n"
"")
        self.name_label.setObjectName("name_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.name_label)
        self.name_lineEdit = QtWidgets.QLineEdit(self.userWidget)
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.name_lineEdit)
        self.id_label = QtWidgets.QLabel(self.userWidget)
        self.id_label.setStyleSheet("font: 80 18pt \"OpenDyslexic\";\n"
"")
        self.id_label.setObjectName("id_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.id_label)
        self.id_lineEdit = QtWidgets.QLineEdit(self.userWidget)
        self.id_lineEdit.setText("")
        self.id_lineEdit.setObjectName("id_lineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.id_lineEdit)
        self.verticalLayout.addWidget(self.userWidget, 0, QtCore.Qt.AlignTop)
        self.buttonWidget = QtWidgets.QWidget(self.center)
        self.buttonWidget.setObjectName("buttonWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.buttonWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.removeButton = QtWidgets.QPushButton(self.buttonWidget)
        self.removeButton.setStyleSheet("QPushButton {\n"
"    font: 80 22pt \"OpenDyslexic\";\n"
"    \n"
"    border-style: outset;\n"
"    background-color: rgb(235, 96, 90);\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgba(59, 84, 120, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"        \n"
"    background-color: rgb(245, 51, 71);\n"
"        transform: tranlateY(-2px)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(69, 69, 69);\n"
"    transfomr: translateY(0px)\n"
"}\n"
"")
        self.removeButton.setObjectName("removeButton")
        self.verticalLayout_3.addWidget(self.removeButton)
        self.returnButton = QtWidgets.QPushButton(self.buttonWidget)
        font = QtGui.QFont()
        font.setFamily("OpenDyslexic")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        font.setKerning(True)
        self.returnButton.setFont(font)
        self.returnButton.setStyleSheet("QPushButton {\n"
"    font: 80 22pt \"OpenDyslexic\";\n"
"    background-color: rgb(104, 140, 183);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: rgba(59, 84, 120, 0);\n"
"    padding: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(127, 182, 187);\n"
"        transform: tranlateY(-2px)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(69, 69, 69);\n"
"    transfomr: translateY(0px)\n"
"}\n"
"")
        self.returnButton.setCheckable(False)
        self.returnButton.setObjectName("returnButton")
        self.verticalLayout_3.addWidget(self.returnButton)
        self.verticalLayout.addWidget(self.buttonWidget, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_4.addWidget(self.center)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_1.setText(_translate("MainWindow", "Remove"))
        self.label_2.setText(_translate("MainWindow", "User"))
        self.name_label.setText(_translate("MainWindow", "Name"))
        self.id_label.setText(_translate("MainWindow", "ID"))
        self.removeButton.setText(_translate("MainWindow", "Remove User"))
        self.returnButton.setText(_translate("MainWindow", "Main page"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
